### ISSUE TITLE
Changing initial guess

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/NLPModels.jl#118]
It's generally useful to run a problem from different starting primal and dual guesses. Currently, it's not possible to change `meta.x0`. What's the best way? I see two options:

1. move `x0` out of `meta` and into the main `NLPModel` struct so users can modify it
2. leave `x0` where it is as the "official" initial guess, and write solvers that take an optional `x0` argument to be used in place of `meta.x0`.

@abelsiqueira @vepiteski

**Comment by abelsiqueira** [comment]
Just to clarify, we can change `meta.x0` accessing its elements, e.g., `meta.x0[1:3] = ones(3)`.

I prefer moving `x0` out of `meta` so that algorithms remain with only one mandatory argument.

**Comment by dpo** [comment]
So much for unmutable structs...

To be clear, `x0` would be *optional* in algorithms, not mandatory.
