### ISSUE TITLE
grad! returns wrong type in ADNLPModels

### ISSUE THREAD

**Issue by vepiteski** [JuliaSmoothOptimizers/NLPModels.jl#123]
g = grad!(nlp, x, g) returns a SubArray{Float64,1,Array{Float64,1},Tuple{UnitRange{Int64}},true}
but  g is an    Array{Float64,1}

causing the next call to grad! issue the error grad! not implemented

JPD

**Comment by Xx-fractale-xX** [comment]
Currently grad!(nlp, x, g) update g but return the wrong type. Temporarily, you can do
```julia
g = zeros(n)
grad!(nlp, x, g)
println(g) # g has been updated and is still an Array{Float64,1}
```
Pull request #124 solve you problem.
