### ISSUE TITLE
Regarding the update to 0.7

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/NLPModels.jl#125]
- JuMP-0.18/MPB will be supported only on 0.6;
- JuMP-0.19/MOI will be supported on both 0.6 and 0.7, but it's not released yet. 
What should be our update strategy?

A possibility to handle 0.7 now, would be to separate JuMP and MPB related things to a separate package (NLPJuMPModel?) and keep it 0.6 while MOI is not released, then this can be updated.

Also, should we be worried about handling both MPB and MOI, and just drop MPB when the time comes?

**Comment by vepiteski** [comment]
As a user/developer, I am puzzled. I wish to upgrade to 0.7 asap. On the 
other hand, most of my code relies on JuMP/MPB.

Personally, I prefer to defer upgrading until the dust has settled 
down... which means living off-beat with the Julia community, unfortunately.

Great to have seen a spectacular announcement of 1.0, but Julia without 
its numerous packages is nothing, so the real upgrade will be completed 
no sooner than when */_all_/* of the packages I rely upon will be 
0.7/1.0 compatible.

Best,

JPD


P.S. My post does not help deciding for the upgrade strategy of 
JuliaSmoothOptimizers, I am afraid!






Le 2018-08-15 à 20:43, Abel Siqueira a écrit :

**Comment by dpo** [comment]
What is the rush to upgrade to 0.7? Maybe we just need to stay with 0.6 for a while?!

I suppose we could extract JumpNLPModel (or whatever) from NLPModels. It would be consistent with what we did for CUTEst and AMPL models.
