### ISSUE TITLE
NLSModels should be considered equal to NLPModels

### ISSUE THREAD

**Issue by vepiteski** [JuliaSmoothOptimizers/NLPModels.jl#127]
I want to include some NLSModels in a test suite for algorithms optimizing general NLPModels. I use as a stopping criterion the counters. I have to struggle to make my stopping test (tired) compatible with Counters and NLSCounters. 

There should be a field counters::Counters  in ALL NLPModels. If the NLSModels use a further set of counters, it should be an additionnal feature, not required in my comparisons.

**Comment by abelsiqueira** [comment]
This won't be a problem after #109, though it may take some time to do that.

For now, though, I recommend using `neval_obj(nlp)` and similar which gets the correct counter.

**Comment by dpo** [comment]
Yes, it's recommended to use the API to access the counters rather than accessing them directly. Does that solve the issue?

**Comment by abelsiqueira** [comment]
Using the counters API should fix it, so I'm closing this.
