### ISSUE TITLE
Missing methods for ADNLPModel

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/NLPModels.jl#130]
```julia
julia> nlp = ADNLPModel(x -> dot(x, x), zeros(2))
julia> neval_obj(nlp)
ERROR: MethodError: no method matching neval_obj(::NLPModels.ADNLPModel)
```

**Comment by abelsiqueira** [comment]
I couldn't reproduce this on Julia 0.6 nor 0.7, with versions v0.4.3 in 0.6 and master in 0.6 and 0.7.

**Comment by dpo** [comment]
Sorry, my bad I think. I must have been using an old version. `master` certainly works. Thanks!
