### ISSUE TITLE
NLPtoMPB moved out from NLPModels - update docs

### ISSUE THREAD

**Issue by pjssilva** [JuliaSmoothOptimizers/NLPModels.jl#141]
Hi. I have just installed NLPModels in both Julia 0.6 and Julia 1.0 and in both the NLPtoMPB function is missing. It seems like you moved it to the package NLPModelsJuMP but the docs for the stable version were not updated. See https://juliasmoothoptimizers.github.io/NLPModels.jl/stable/api.html#NLPModels.NLPtoMPB 

Note that in Julia 0.6 the version that is installed is reported as v"0.5.0" and in Julia 1.0 v"0.6.1". Since the version 0.6.1 is marked as the stable version, hence I am talking about the documentation to the stable version. The documentation of the dev version looks OK (the function is not there anymore).

**Comment by abelsiqueira** [comment]
Thanks @pjssilva, you're right, `JuMP/MPB` related functions were moved to `NLPModelsJuMP`, and the docs weren't updated yet due to lack of a release.

**Comment by abelsiqueira** [comment]
Stable documentation is now correct: http://juliasmoothoptimizers.github.io/NLPModels.jl/stable/
