### ISSUE TITLE
Default grad, hprod, cons, etc.

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/NLPModels.jl#168]
Could we have the non-inplace versions of methods call the inplace versions by default?
```julia
# NLPModels.jl
function grad(nlp::AbstractNLPModel, x::AbstractVector)
  gx = zeros(eltype(x), nlp.meta.nvar)
  return grad!(nlp, x, gx)
end
```
That would help with defining new model, such as the ones replacing `SimpleNLPModel`.

**Comment by dpo** [comment]
Definitely!
