### ISSUE TITLE
Change docstrings

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/NLPModels.jl#179]
From
```julia
"""`foo`
"""
```
to
```julia
"""
    foo
"""
```

**Comment by xhu4** [comment]
I think I can handle this in my PR #184.

**Comment by dpo** [comment]
Hi @xhu4 ! Many thanks for your contributions! It would be great to keep PRs separate though. It makes it much easier for us to review and it keeps commits focused on specific topics.
