### ISSUE TITLE
Remove `rows` and `cols` for coord functions

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/NLPModels.jl#192]
Since `coord` functions can't touch `rows` and `cols`, we should remove these arguments.

**Comment by dpo** [comment]
That will require changes to

- [ ] CUTEst.jl
- [ ] AmplNLReader.jl
- [ ] NLPModelsIpopt.jl
- [ ] NLPModelsKnitro.jl
- [ ] CaNNOLeS.jl
