### ISSUE TITLE
Sparse dercheck

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/NLPModels.jl#260]
When checking a Jacobian against finite differences, it would be useful to have an option to assume that the sparsity structure is correct and avoid computing all finite differences.

**Comment by abelsiqueira** [comment]
Moved to https://github.com/JuliaSmoothOptimizers/NLPModels.jl/issues/344

**Comment by abelsiqueira** [comment]
Moved to https://github.com/JuliaSmoothOptimizers/NLPModelsTest.jl/issues/4
