### ISSUE TITLE
Ambiguous methods

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/NLPModels.jl#275]
Trying to follow the tutorial at https://juliasmoothoptimizers.github.io/NLPModels.jl/stable/guidelines/#bare-minimum-1.

Consider the definition:
```julia
using NLPModels

mutable struct MyModel <: AbstractNLPModel
  meta :: NLPModelMeta
  counters :: Counters
end

MyModel() = MyModel(NLPModelMeta(10, nnzj=10), Counters())

function NLPModels.jac_structure!(model::MyModel, rows::AbstractArray{<: Integer}, cols::AbstractArray{<: Integer})
  rows .= 1:10
  cols .= 1:10
  return rows, cols
end

function NLPModels.jac_coord!(model::MyModel, x::AbstractArray, vals::AbstractArray)
  vals .= rand(10)
  return vals
end
```

Then:
```julia
julia> model = MyModel()
MyModel(Minimization problem Generic
nvar = 10, ncon = 0 (0 linear)
, Counters(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0))

julia> jac(model, model.meta.x0)
ERROR: MethodError: jac_structure!(::MyModel, ::Array{Int64,1}, ::Array{Int64,1}) is ambiguous. Candidates:
  jac_structure!(::AbstractNLPModel, ::AbstractArray{#s56,1} where #s56<:Integer, ::AbstractArray{#s55,1} where #s55<:Integer) in NLPModels at /Users/dpo/.julia/packages/NLPModels/fga5y/src/NLPModels.jl:248
  jac_structure!(model::MyModel, rows::AbstractArray{T,N} where N, cols::AbstractArray{T,N} where N) where T<:Integer in Main at /private/tmp/test_nlp.jl:11
Possible fix, define
  jac_structure!(::MyModel, ::AbstractArray{T<:Integer,1}, ::AbstractArray{T<:Integer,1})
Stacktrace:
 [1] jac_structure(::MyModel) at /Users/dpo/.julia/packages/NLPModels/fga5y/src/NLPModels.jl:240
 [2] jac(::MyModel, ::Array{Float64,1}) at /Users/dpo/.julia/packages/NLPModels/fga5y/src/NLPModels.jl:274
 [3] top-level scope at REPL[26]:1
```

The suggested fix doesn't appear to be valid syntax.

I tried
```julia
function NLPModels.jac_structure!(model::MyModel, rows::AbstractArray{T}, cols::AbstractArray{T}) where T <: Integer
```
but I get the same kind of error.

The solution appears to be to implement `jac(model::MyModel, x::AbstractVector)`, because it will call `jac_structure!()` and `jac_coord!()` with concrete vectors, which removes the ambiguity.

Alternatively, we could implement `jac_structure()` and `jac_coord()`.

**Comment by abelsiqueira** [comment]
It needs to be `AbstractVector`, not `AbstractArray`. It's not immediately clear from the error, but the ambiguity comes from one function being defined for `AbstractArray{T,N}` and the other for `AbstractArray{<: Integer,1}`.
Similar errors appear to me sometimes, and I have thought about removing these types from the vectors, which should simplify the code. Not sure what kind of new problems will appear, though.

**Comment by dpo** [comment]
Gee, thanks! The real question here is **why would I write** `AbstractArray`????
