### ISSUE TITLE
LLSModels no longer accept LinearOperators

### ISSUE THREAD

**Issue by vepiteski** [JuliaSmoothOptimizers/NLPModels.jl#281]
My code breaks and I have no simple workaround. I can't construct the matrix which is implicit in the expression Ac*X*Ar'  where X is a bitmap. The linear operator is constructed by reshaping the vector x to the matrix X and computing Ac*X*Ar'  and then reshaping back the result to  matrix format. The implicit matrix would be HUGE.

**Comment by abelsiqueira** [comment]
I'm working on the additional `LLSModels` mentioned in #273, soon I'll post an update.

**Comment by abelsiqueira** [comment]
Moved to https://github.com/JuliaSmoothOptimizers/LLSModels.jl/issues/1
