### ISSUE TITLE
Including parameters (aka fixed variables) ?

### ISSUE THREAD

**Issue by raphaelchinchilla** [JuliaSmoothOptimizers/NLPModels.jl#299]
Suppose one needs to solve
\min_x c(x,p)
where c(x,p) is a family of cost functions parametrized by p. 

If one wants to solve the problem for multiple values of p, compiling the code multiple times tend to be very slow. Therefore, it is often possible to define some "fixed" parameters. In JuMP one can do that either by using @NLparameters or using fix(). 

Is there any equivalent for that in NLPModels or NLPModelsJuMP?

**Comment by abelsiqueira** [comment]
Hi @raphaelchinchilla, in NLPModels that would depend on the implementation of the model, not on anything inside NLPModels itself.
Here's an example with ADNLPModel:
```julia
f(x,a) = (x[1] - a)^2 + 4 * (x[2] - x[1]^2)^2
g(x) = f(x,a)  # a is not used at construction!
nlp = ADNLPModel(g, zeros(2));
a = 1
grad(nlp, [a; a^2]) # Now a is used
a = 2
grad(nlp, [a; a^2]) # Now a is used again
```
Above, `a` is a parameter. Your control over it is a little limited, though. NLPModelsJuMP works by defining your JuMP model and calling `MathOptNLPModel(model)`. So maybe you can define your parameters in the `model`, and keep it around to modify. I personally never used parameters in JuMP, so I'm sure how they work.

An alternative to keeping a parameter would be to define your model manually. We have done exactly that in two applications:[RegularizationModel](https://github.com/JuliaSmoothOptimizers/RegularizationModel.jl/blob/master/src/RegularizationModel.jl#L17-L18) and [AugLagModel](https://github.com/CiDAMO/Percival.jl/blob/master/src/AugLagModel.jl#L17-L21). Notice that these are not released, the first is just for tutorial purposes and the second is from a WIP. But if you decide to implement your own model, we have resources for that.

**Comment by abelsiqueira** [comment]
Regarding the "fixed variables" in your title, if a model has `lvar[i] == uvar[i]`, that variable is fixed. It is not a parameter, as they'll be used on the derivatives, they'll have initial values, and ideally you shouldn't change `lvar` and `uvar`. But depending on your solver and use case, that may work.
