### ISSUE TITLE
hess_coord consistency

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/NLPModels.jl#33]
Testing #32, I found that `JuMPNLPModel.hess_coord` returns repeated (i,j) on (rows,cols). Should we squash these repeated coordinates, or allow? `sparse(I, J, V)` allows it.

**Comment by dpo** [comment]
I propose to allow it because `sparse(I, J, V)` allows it. The documentation should make it clear that there may be repeated indices though.

**Comment by abelsiqueira** [comment]
Agreed
