### ISSUE TITLE
Slack c(x) inconsistency

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/NLPModels.jl#34]
When the models define the inequalities differently, `lcon` and `ucon` will be different and therefore `c(x) - s`, will give different results, which can't be corrected without privileged information.
Options:
- Change the ~~models~~ problems (Seems best)
- Ignore `cons` on consistency for slack models
- "Cheat" (Use privileged information)

Related to #32

**Comment by dpo** [comment]
In what models does this happen?

**Comment by abelsiqueira** [comment]
Happened on hs10. Ampl and Simple defined it one way, while JuMP and CUTEst another.
Looks like hs14 is also going to have the same problem. I can the fix the models, though.

**Comment by abelsiqueira** [comment]
I've change the Ampl problems hs10.nl and hs14.nl and SimpleModel from hs10, and it's working now.
