### ISSUE TITLE
Is `meta.minimize` useful?

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/NLPModels.jl#341]
A bit of a provocative question... According to the documentation, it should be set as true if it is a minimization problem.
- no NLPModel-specializations are offering this option in their constructors.
- JSO-compliant solvers aren't using it.

Wouldn't it be useful to remove it and state in the documentation that we handle the minimization problem only?

**Comment by dpo** [comment]
It’s a useful question. AmplNLReader sets it: https://github.com/JuliaSmoothOptimizers/AmplNLReader.jl/blob/master/src/ampl_model.jl#L40. It may be the only one.

**Comment by amontoison** [comment]
I use it in `NLPModelsJuMP` : https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl/blob/master/src/moi_nlp_model.jl#L60

**Comment by abelsiqueira** [comment]
Well, the best models to set it would be the ones based on modelling. So at least we know that there models that can be used to test it, and that we shouldn't just throw the flag away.
Now the question is what should we do for the solvers.

I looked into `Ipopt.jl` and it does use `:Min` and `:Max` to set Ipopt's objective scaling.
`NLPModelsIpopt.jl` seems to ignore it. Should we try to fix it and add tests? Should all solvers?

**Comment by dpo** [comment]
Yes I think all solvers should. It’s inefficient for us to handle it inside the model as we would have to change the sign of every gradient and Hessian in place at every evaluation.

**Comment by tmigot** [comment]
Reviewed everywhere :).
