### ISSUE TITLE
LBFGS approx of Hessian

### ISSUE THREAD

**Issue by mohamed82008** [JuliaSmoothOptimizers/NLPModels.jl#343]
I searched the repo for quasi-Newton and found an old PR #28 but it seems that LBFGSModel was removed? Is there an alternative to do quasi-Newton optimization in `JSOSolvers.tron` used in `Percival`?

**Comment by dpo** [comment]
Things just moved around quite a bit. The quasi-Newton model is here now: https://github.com/JuliaSmoothOptimizers/NLPModelsModifiers.jl/blob/master/src/quasi-newton.jl

**Comment by mohamed82008** [comment]
cool thanks!
