### ISSUE TITLE
non-finite values in constraint and objective

### ISSUE THREAD

**Issue by tpapp** [JuliaSmoothOptimizers/NLPModels.jl#350]
*(I tried to check for an existing issue about this and couldn't find one, also, I am not sure if this is the right repo for it, if not, please move)*

Despite best effort, occasionally non-finite values (`Inf` and `NaN`) end up in the objective and/or the constraints. This is exacerbated by AD: the value itself can be finite, but partials may not be, or even the first derivative can be all finite but the Hessian not.

My impression is that currently this suite of optimizers has no standard way of dealing with this, things will eventually error but not immediately as eg `NaN` trickle through a calculation, so debugging can be tricky (cf JuliaSmoothOptimizers/Percival.jl/issues/50).

I would like to propose the following: solvers should check for finiteness of results from `obj`, `grad`, `hess`, `cons`, & friends, and *throw an error by default*, eg `DomainError`. This check is fairly cheap (`all(isfinite, ...)`).

Solvers for which this makes sense can do something instead, eg backtrack to a know valid value.

**Comment by vepiteski** [comment]
This is (among others) what Stopping is all about!  See 
https://github.com/vepiteski/Stopping.jl

JPD


Le 21-05-11 à 11 h 56, Dominique a écrit :

**Comment by abelsiqueira** [comment]
I agree, I'll create an issue on SolverTest to create a test for that.

**Comment by abelsiqueira** [comment]
Moved to https://github.com/JuliaSmoothOptimizers/SolverTest.jl/issues/9, thanks for opening the issue.
