### ISSUE TITLE
Symmetric hessians

### ISSUE THREAD

**Issue by vepiteski** [JuliaSmoothOptimizers/NLPModels.jl#352]
Each time I quickly use a `H = hess(...)` I forget that in order to get the full matrix, one has to do `Symmetric(H, :L)`... I then dig to find the cause of the erroneous computation. This is counter-intuitive.

May I recommend to return the full matrix by default and leave an option to return only the triangular part? Moreover, the default of the Symmetric  function is  :U, so that `Symmetric(H)` does not work. Why not returning the upper triangular?

**Comment by dpo** [comment]
I think we return the lower triangle because that’s what AMPL or CUTEst does. I don’t think we want to return the full matrix; that would be very inefficient for large problems, but perhaps `hess()` could return `Symmetric(H, :L)`. What do you think @abelsiqueira ?

**Comment by abelsiqueira** [comment]
The issue is `Symmetric(sparse)`. Last time we checked it was not efficient.

**Comment by abelsiqueira** [comment]
But if we assume that "if you want efficiency, you should use _coord and _structure", then I'm not opposed.

**Comment by dpo** [comment]
Wasn’t that fixed last fall or so?

**Comment by abelsiqueira** [comment]
I honestly don't know, sorry. I might be outdated.

**Comment by dpo** [comment]
https://discourse.julialang.org/t/slow-sparse-matrix-vector-product-with-symmetric-matrices/3968/34?u=dpo

**Comment by abelsiqueira** [comment]
In that case, I retract my objection.

**Comment by abelsiqueira** [comment]
NLPModels 0.17 supports this now.
