### ISSUE TITLE
Change SimpleNLPModel to AutodiffNLPModel and create UserNLPModel

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/NLPModels.jl#36]
SimpleNLPModel is not very efficient, but as an automatic differentiation tool is useful. To make it more efficient we'll have to use Autodiff and ReverseDiff. This probably means that it won't be as simple.

On the other hand, a user wanting to efficiently define specific functions might want to pass each of them.

**Comment by dpo** [comment]
How about `ADModel` or `ADNLPModel`? I think we could stick with `SimpleNLPModel` to mean user-defined functions. What do you think?

**Comment by abelsiqueira** [comment]
Yes, that's valid. `ADNLPModel` and `SimpleNLPModel` then.

**Comment by dpo** [comment]
Done in #39.
