### ISSUE TITLE
Release and move development to master

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/NLPModels.jl#37]

**Comment by dpo** [comment]
We should probably address #41 and #49. Then I think we'll be in good shape for a first release.

**Comment by dpo** [comment]
I think we're ready to merge `develop` into `master` and remove the `develop` branch.

**Comment by abelsiqueira** [comment]
Agreed

**Comment by dpo** [comment]
#56 closed the `develop` branch.

**Comment by dpo** [comment]
Is this ready for a first release?

**Comment by abelsiqueira** [comment]
I think so.

**Comment by dpo** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/6709

**Comment by dpo** [comment]
Merged.
