### ISSUE TITLE
Better support for linear constraints

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/NLPModels.jl#377]
As discussed with @tmigot and @dpo, create separate API for linear and nonlinear constraints.

**Comment by tmigot** [comment]
As a small note, in Knitro (see [PR 72 in NLPModelsKnitro.jl](https://github.com/JuliaSmoothOptimizers/NLPModelsKnitro.jl/pull/72)), the constraint is expected to have the form:
```
x -> c(x) + A * x
```
where `A` is given separately.
