### ISSUE TITLE
MathProgBase wrapper

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/NLPModels.jl#38]
Create a MPB wrapper. Possibly supersedes JuMPNLPModel

**Comment by dpo** [comment]
We should have a way to convert any `AbstractNLPModel` to a MathProgBase model. That would apply transparently to `AmplModel`s, `CUTEstModel`s, etc. See #43. A good starting point is probably [`AMPLMathProgInterface.jl`](https://github.com/mlubin/AMPLMathProgInterface.jl).

**Comment by dpo** [comment]
Done in #45.
