### ISSUE TITLE
Issue with AbstractNLPModel

### ISSUE THREAD

**Issue by tnnguyen103** [JuliaSmoothOptimizers/NLPModels.jl#386]
I tried to declare a struct which is a subtype of AbstractNLPModel:
```
using NLPModels

struct MyModel <: AbstractNLPModel
    meta :: NLPModelMeta
    counters :: Counters
end
```

However, I get an error as below
```
invalid subtyping in definition of MyModel

Stacktrace:
 [1] top-level scope at In[69]:3
 [2] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1091
```
Could you please guide me how to fix this error? Thanks in advance.

**Comment by abelsiqueira** [comment]
Hi @tnnguyen103, `AbstractNLPModel` has types now. I think you can follow https://juliasmoothoptimizers.github.io/NLPModels.jl/latest/guidelines/.

Also, what tutorial/docs were you following, so we can update it?

Thanks for the issue.

**Comment by dpo** [comment]
You seem to be missing the parametric types. Something like:
```
struct MyModel{T, S} <: AbstractNLPModels{T, S}
  meta :: NLPModelMeta{T, S}
  counters :: Counters
end
```

**Comment by tnnguyen103** [comment]
Thank @abelsiqueira and @dpo! I followed the doc on the following page
https://juliasmoothoptimizers.github.io/NLPModels.jl/stable/guidelines/
