### ISSUE TITLE
reset! function

### ISSUE THREAD

**Issue by geoffroyleconte** [JuliaSmoothOptimizers/NLPModels.jl#437]
Hi, I don't know if this is an issue, but when using `reset!(nlp)`, the data of `nlp` are also reset (not mentionned in the doc).
Should `reset!` not call `reset_data!`? Or should the doc of `reset!`be modified?

https://github.com/JuliaSmoothOptimizers/NLPModels.jl/blob/0b36c4f59ebf4d61f73203e9917549256c999661/src/nlp/counters.jl#L114

**Comment by tmigot** [comment]
Thanks @geoffroyleconte for catching this!
You are right, the documentation is incomplete here. Could you open a PR to fix it?
