### ISSUE TITLE
Out of date link in Guidelines

### ISSUE THREAD

**Issue by votroto** [JuliaSmoothOptimizers/NLPModels.jl#440]
A full list of fields [links to a deleted file](https://github.com/JuliaSmoothOptimizers/NLPModels.jl/blob/0d2ff8036cb2206e225c8cb900ecbfbdb787ffc8/docs/src/guidelines.md?plain=1#L32) `src/nlp_types.jl`, the correct destination is probably [src/nlp/meta.jl](https://github.com/JuliaSmoothOptimizers/NLPModels.jl/blob/0d2ff8036cb2206e225c8cb900ecbfbdb787ffc8/src/nlp/meta.jl#L32)

**Comment by tmigot** [comment]
Thanks @votroto for catching that. I opened a PR to fix it and #441 will make sure we detect this type of error in the future.
