### ISSUE TITLE
Documentation: inconsistency in whether constraints are zero

### ISSUE THREAD

**Issue by timholy** [JuliaSmoothOptimizers/NLPModels.jl#460]
Consider [HS62](https://github.com/JuliaSmoothOptimizers/OptimizationProblems.jl/blob/65bda82047287f09d261b86c968256eb21ae8df0/src/PureJuMP/hs62.jl), for which the constraint is
```julia
x[1] + x[2] + x[3] - 1 == 0
```
and the initial value is `x0 = [0.7, 0.2, 0.1]` which sums to 1. Thus you expect the initial constraint value to be zero. However:
```julia
julia> using NLPModels, NLPModelsJuMP, OptimizationProblems.PureJuMP

julia> nlp = MathOptNLPModel(hs62());

julia> cons(nlp, nlp.meta.x0)
1-element Vector{Float64}:
 0.9999999999999999
```

My suspicion is that the bug is in this package, but I'm unsure. It seems likely that it's neglecting to incorporate the constant offset in the JuMP model?

**Comment by timholy** [comment]
Right. To be clear, the way this came up was using OptimizationProblems.jl as a repository of test problems for an external optimizer, and then being surprised that the solution wasn't as stated in the documentation. It's really just a documentation issue, but one that's a significant "gotcha" for external consumers of your interface.

**Comment by dpo** [comment]
Thanks for bringing this to our attention!
