### ISSUE TITLE
Default behavior for `nln_nnzj`

### ISSUE THREAD

**Issue by sshin23** [JuliaSmoothOptimizers/NLPModels.jl#475]
Hi JSO team! 

Recent change in https://github.com/JuliaSmoothOptimizers/NLPModels.jl/pull/468 is causing errors in ExaModels.jl and MadNLP.jl, both of which only sets `nnzj`. I was wondering if the default behavior for `nln_nnzj` be made e.g., `nln_nnzj = nnzj - lin_nnzj`?

**Comment by amontoison** [comment]
Hi Sungho!

We will have a similar issue if the user only provides `nln_nnzj`.
I'm wondering if the best solution is not fix it in MadNLP.jl and ExaModels.jl like you did.

cc @tmigot

**Comment by tmigot** [comment]
Even though I agree with @amontoison , it makes sense to me that user not implementing the linear API shouldn't have to specify `nln_nnzj`. We could update version 0.21.2 with #477 if you both agree.

**Comment by sshin23** [comment]
@tmigot I agree that user not implementing the linear API shouldn't have to specify `nln_nnzj`. From the user's perspective, it will be a net improvement. Of course, there's something I'm missing; we will respect NLPModels.jl dev's decision. For now, we can remove NLPModels.jl v0.21 from the compat entry of MadNLP and ExaModels

**Comment by tmigot** [comment]
@sshin23 released 21.3 should fix your issue

**Comment by sshin23** [comment]
Thanks, @tmigot and @amontoison
