### ISSUE TITLE
Keep ExaModels.jl and MadNLP.jl for breakage tests

### ISSUE THREAD

**Issue by amontoison** [JuliaSmoothOptimizers/NLPModels.jl#488]
In #483, @tmigot updated the workflow for breakage but removed the packages of our colleagues François and Sungho.
We should keep them because we already broke these packages with a minor release in the past.

**Comment by dpo** [comment]
I don't think it's for us to check breakage of outside packages, but for them to properly manage the version they use and report bugs, if any.

**Comment by amontoison** [comment]
I agree but we should also not break them with minor releases.
It was totally our fault.

**Comment by dpo** [comment]
We test on FreeBSD to check that the code runs on FreeBSD, not to verify that we don't break other packages. Our Breakage workflow is already extensive enough. Breakage  checks in external packages should happen in PRs to those packages' repos. That's what we do. We should just be careful with minor/major version bumps.
