### ISSUE TITLE
Test all functions on all interfaces

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/NLPModels.jl#5]
- Models
  - [x] SimpleNLPModel
  - [x] JuMPModel
  - [x] AMPLModel
  - [x] CUTEstModel
 - Functions (and inplace versions)
  - [x] obj(nlp, x)
  - [x] grad(nlp, x)
  - [x] hess(nlp, x)
  - [x] hess(nlp, x, y=y)
  - [x] hprod(nlp, x, v)
  - [x] hprod(nlp, x, v, y=y)
  - [x] cons(nlp, x)
  - [x] jac(nlp, x)
  - [x] jprod(nlp, x)
  - [x] jtprod(nlp, x)

**Comment by dpo** [comment]
`JuMPModel` doesn't support Jacobian-vector products (yet). `AmplModel` doesn't either and likely won't.

**Comment by abelsiqueira** [comment]
How do you wanna handle this jprod? Use a default build-the-matrix-then-prod implementation? Lose the requirement? PR them?

**Comment by dpo** [comment]
I suppose the most robust temporary solution would be to evaluate the Jacobian and then multiply.

**Comment by abelsiqueira** [comment]
I'm gonna have to change some sizes in the tests to have compatibility with CUTEst. I hope it's that simple.

**Comment by abelsiqueira** [comment]
How do I convert mod to nl? Can I do it without the ampl executable?

**Comment by dpo** [comment]
You need the ampl executable to generate a nl file. That's what it's for.

**Comment by abelsiqueira** [comment]
Regarding the CUTEst compatibility, there will be a PR shortly, but there are some issues with the problems:
- GENROSE: Even with 100 variables (changing the SIF), there is considerable error. obj returns and error of 4, where f ~ 1e6. The maximum error expected is 1e6 * 1e-10 = 1e-4, and all other problems find it, so it is the way CUTEst compute it that gives such a large error.
- HS11: The constraint in CUTEst is the negative of the one on the rest.
- HS14: Something similar to HS11, haven't checked yet.

**Comment by dpo** [comment]
If the problem formulations differ, we should make them what the official reference says (e.g., the HS book).

For genrose, what is the error that you are measuring?

**Comment by abelsiqueira** [comment]
I'm measuring function values from other models and CUTEst.
The values are (for some random x0)
````
1.4995852340157446e6 # Other
1.4995553998517566e6 # CUTEst
````
The error was about 29.83, while the allowed error rtol * fmin was ~ 0.17876 using rtol = eps(Float32).

**Comment by abelsiqueira** [comment]
I removed from the consistency the following functions, which are not meant for every model: `writesol`, `varscale`. `lagscale` and `conscale`.
The following are not implemented for every model, should they be required? `jth_con`, `jth_congrad`, `jth_sparse_congrad`, `jac_coord`, `jth_hprod`, `ghjvprod` and `hess_coord`.

I'll add the requirement of adding counters and reset!

**Comment by dpo** [comment]
No method is required, but all can be overloaded.

**Comment by abelsiqueira** [comment]
I thought the ones on `consistency.jl` would be required for all models. But if not, then nevermind the first paragraphs.

**Comment by abelsiqueira** [comment]
I added the CUTEst model, changing the other models. I figured a way to create genrose the way I wanted, and increased `rtol` to pass the tests. However, travis takes too long on the genrose tests, and fails.
I'm gonna get a different unconstrained problem with less variables.

**Comment by dpo** [comment]
Sounds good.

**Comment by dpo** [comment]
Can this be closed?

**Comment by abelsiqueira** [comment]
Yes, thank you.
