### ISSUE TITLE
Simple queries on NLPModelMeta and AbstractNLPModel for type of problem

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/NLPModels.jl#51]
Is it useful enough? All oneliners (so far)

- is_free
- is_unc
- all_cons_linear
- all_cons_equality
- all_cons_inequality

**Comment by dpo** [comment]
What does `is_free` mean? How about the names
* `unconstrained(model)`
* `equality_constrained(model)`
* `inequality_constrained(model)`
* `linearly_constrained(model)` (not my favorite)

Another useful one would be
* `bound_constrained(model)`

**Comment by abelsiqueira** [comment]
`is_free` = free variables, i.e., no bounds, i.e. `!bound_constrained(model)`.
That naming works too. I though Julia had a convention for `is`, but I couldn't find.

**Comment by abelsiqueira** [comment]
I'll use `bound_constrained` then.

**Comment by dpo** [comment]
Closed by #55.
