### ISSUE TITLE
Consistency

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/NLPModels.jl#6]
All models should

 - [x] return the same Hessian (only triangular);
 - [x] use the same Lagrangian (s*f(x) + sum y_ic_i + zl_i(x_i - l_i) + zu_i(u_i-x_i) );
 - [x] implement all functions (see #5);
 - [x] have the same meta;
 - [x] have the same counters.

There may be some exceptions. *SlackModel* for instance is consistent only for equality constrained problems.

**Comment by abelsiqueira** [comment]
While trying to make meta the same for JuMP and AMPL, I noticed that NLP has a lot of information. Some very useful for our future selector, but very hard to implement for some models (CUTEst).
So, instead of having the same meta, I'll consider only a more reasonable subset of the fields.

Furthermore, do we want all those fields in meta? I think it was originally develop thinking of AMPL, but won't we focus on continuous NLP?

**Comment by dpo** [comment]
There's no need to fill in all fields. AmplNLReader can be easily modified to fill them all in (it currently doesn't) but I don't see any harm in keeping them around. Because Julia doesn't support inheritance, it's not easy to extend a "meta" type.

**Comment by abelsiqueira** [comment]
Understood. My concern here was with the bounds on the constraints, but I'll do something different now and still mantain some consistency: I'll compare c(x) - L and c(x) - U, instead of only c(x). So JuMP and AMPL should match.

**Comment by dpo** [comment]
What was the concern with c(x)? Were you trying to determine the type of each constraint?

**Comment by abelsiqueira** [comment]
I am trying to avoid specific cases like [this](https://github.com/JuliaOptimizers/NLPModels.jl/blob/develop/test/jump_vs_ampl.jl#L31-L36).

**Comment by dpo** [comment]
It's important to make the difference between those types of constraints though, isn't it?

**Comment by abelsiqueira** [comment]
Possibly, but I'm just avoiding it at the consistency tests.

**Comment by abelsiqueira** [comment]
I'll have to make a little change on the ampl and jump models for counter consistency.
`jprod` is implemented by calling `jac` which increases the `jac` counter, so I'll have to stop calling `jac`, and manually call whatever is being called instead.

**Comment by abelsiqueira** [comment]
Alternatively, I can sum `jac`, `jprod` and `jtprod` counters, which looks better than the alternative, and less code is changed.

**Comment by dpo** [comment]
I think we should count `jac`, `jprod` and `jtprod` separately as those are important when you evaluate the performance of a solver. *How* the modeling language gives access to `jac, `jprod`, and `jtprod` is important but is not the solver's concern.

**Comment by abelsiqueira** [comment]
I'll change jprod on jumpmodel.jl and amplmodel.jl to not call jac then, and update #19.

**Comment by dpo** [comment]
It's ok if `jprod` calls `jac`; it's a limitation of the modeling language. It just shouldn't update the number of Jacobian evals, only the number of Jacobian-vector products.

**Comment by abelsiqueira** [comment]
Okay, so after calling `jac()`, I'll decrease `njac` and increase `jprod`, is that good?

**Comment by dpo** [comment]
Yes, that's what I was thinking.

**Comment by abelsiqueira** [comment]
Closed by #19
