### ISSUE TITLE
Add options for what is required of a MathProgNLPModel

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/NLPModels.jl#63]
Currently, `MathProgNLPModel(problem)` [sets up the structure for the Hessian and the expression graph](https://github.com/JuliaSmoothOptimizers/NLPModels.jl/blob/master/src/mpb_model.jl#L46), which takes large amounts of time for some problems. There should be an option to select what should be generated.

For example,

``` julia
using OptimizationProblems
prob = penalty2(5000)
model = MathProgNLPModel(prob)
```

takes several minutes, but if we request only

``` julia
MathProgBase.initialize(eval, [:Grad, :Jac, :HessVec])
```

then,

``` julia
julia> model = MathProgNLPModel(prob);

julia> @time model = MathProgNLPModel(prob);
  0.017955 seconds (503 allocations: 19.509 MB, 18.29% gc time)
```

**Comment by dpo** [comment]
cf: https://groups.google.com/forum/#!topic/julia-opt/ZLBfeuvtJzU

**Comment by abelsiqueira** [comment]
Closing this because #64 was closed.
