### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/NLPModels.jl#73]
I thinks it's time for a new release. Also, I'd like to create a CUTEst release with stable NLPModels.

**Comment by dpo** [comment]
Sounds good.

**Comment by dpo** [comment]
I think we have to tell Travis/Appveyor to tolerate errors in 0.6. Otherwise the badges suggest that the build fails.

**Comment by abelsiqueira** [comment]
Could not make it for appveyor. Tried some tinkering and made some searching. Couldn't find a case where the fail was for environment variables.

**Comment by abelsiqueira** [comment]
Furthermore, Windows 0.5 is failing due to https://github.com/JuliaOpt/Ipopt.jl/issues/77

**Comment by abelsiqueira** [comment]
Hum, I found out in gitter how to do it. However, there is no indication on appveyor that those configurations are allowed to fail, except for it passing when the others pass and those fail.
In our case, it will still appear failing.
