### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/NLPModels.jl#84]
Enable [attobot](https://github.com/integration/attobot)?
Release 0.2.0?

**Comment by dpo** [comment]
Done. Sorry for the delay.

**Comment by abelsiqueira** [comment]
Thank you

**Comment by abelsiqueira** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/8602

**Comment by dpo** [comment]
Thank you! Can this be closed?
