### ISSUE TITLE
Proposition: Change `meta` (add `get(nlp, :thing)`)

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/NLPModels.jl#92]
Instead of using `nlp.meta.nvar`, use `get(nlp, :nvar)` or `getfield`.

In particular, a related problem is in the `NLS` #91 `nls_meta`. Since we don't have OO, we can't have `nls_meta` extending `meta` only including `nequ`. With the proposed change, though, we can define

```
abstract AbstractNLSMeta
type NLSMeta <: AbstractNLSMeta
  meta :: AbstractNLPMeta
  nequ :: Int
end
abstract AbstractNLSModel
type LLSModel <: AbstractNLSModel
  meta :: NLSMeta
  A :: Matrix
  b :: Vector
end

meta(nlp :: AbstractNLPModel) = nlp.meta
meta(nls :: AbstractNLSModel) = nls.meta.meta
get(nlp :: AbstractNLPModel, name :: Symbol) = getfield(meta(nlp), name)
```

**Comment by dpo** [comment]
We could probably use an overarching `AbstractMeta`. Using metaprogramming, we can probably define methods
```julia
nvar(model::AbstractNLPModel) = model.meta.nvar
ncon(model::AbstractNLPModel) = model.meta.nvar
...
```
which may look more intuitive than `get()`!?

**Comment by abelsiqueira** [comment]
Yes, this also works for my use case. I'll try this change on the `nls` branch, and if it looks good I'll refactor.

**Comment by abelsiqueira** [comment]
What I missed before is that these names are fairly common choices for variables, and thye would conflict.
```julia
nvar = nvar(nlp)
...
nvar(nlp) # error in the same scope
```
On the other hand, usually you would either have a single `nvar`, so no need to call `nvar(nlp)` again, or multiple `nvar`, in which case, you'd have to name it better.
The only really conflicting use case I found was
```julia
function FeasModel(nlp :: AbstractNLPModel; name::String = name(nlp))
  ...
end
```
in which case, `name::String` had to be changed.

Do you see this becoming a problem?

**Comment by abelsiqueira** [comment]
I was wrong, `nvar = nvar(nlp)` won't work inside a function.
```julia
foo(a) = a+1
function bar()
  foo = foo(2)
end
bar() # ERROR: UndefVarError: foo not defined
```
I think the best approach here would be create a descriptive function call, e.g. `nvar = number_of_variables(nlp)`. But then, the meta cleanup should be done first.

**Comment by dpo** [comment]
How about `get_nvar()`? There's a long discussion here: https://github.com/JuliaLang/julia/issues/16770

**Comment by abelsiqueira** [comment]
Not implementing as discussed in #237.
